version: '3.8'

services:
  postgres:
    image: postgres:16-alpine
    container_name: ai-studio-postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: aistudio
      POSTGRES_PASSWORD: aistudio_dev_password
      POSTGRES_DB: ai_studio
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U aistudio']
      interval: 10s
      timeout: 5s
      retries: 5

  # Optional: PgAdmin for database management
  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: ai-studio-pgadmin
    restart: unless-stopped
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@aistudio.local
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - '5050:80'
    depends_on:
      - postgres

volumes:
  postgres_data:
    driver: local

